38 Allow focus log panel: Fix
StefanHolst/opentap-tui pull request #40
Opened 2022-07-12 14:27 UTC by rmadsen-ks

- added support for tabbing to the log panel view.
- added support for shift-tab which cycles focus back instead of forward.

2022-07-13 08:02 UTC, frederikja163 requested changes
I would prefer if we save the menus to a list in the order we want to tab through them. Then we could also add the rest of the menus to this list. Like the toolbar.

2022-07-13 14:07 UTC, StefanHolst requested changes
Just a minor comment

2022-07-13 14:07 UTC, StefanHolst commented on OpenTAP.TUI/OpenTAP.TUI.cs
>              if (keyEvent.Key == Key.Tab || keyEvent.Key == Key.BackTab)
I think this behaviour could be achieved by just removing this code. This already happens with arrow keys

2022-08-12 08:15 UTC, closed without merging

2022-08-12 08:15 UTC, frederikja163 commented
Closing as the issue is no longer considered an issue. See #38